theme: jekyll-theme-slate
title: “MEIJUN CHEN”
description: "What you will find here are links to projects, publications, and repositories related to the former."
plugins:
  - jemoji
url: https://github.com/Cherxxxx/Cherxxxx/edit/main/_config.yml
markdown: kramdown
