theme: jekyll-theme-slate
title: MEIJUN CHEN
description: What you will find here are links to projects, publications, and repositories related to the former.
plugins:
  - jemoji
url: "https://cherxxxx.github.io/"
markdown: kramdown
